# permissions for end users to edit networktests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: networktest-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: networktester
    app.kubernetes.io/part-of: networktester
    app.kubernetes.io/managed-by: kustomize
  name: networktest-editor-role
rules:
- apiGroups:
  - edgeworks.no
  resources:
  - networktests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - edgeworks.no
  resources:
  - networktests/status
  verbs:
  - get
