---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: networktester-controller
rules:
- apiGroups:
  - edgeworks.no
  resources:
  - networktests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - edgeworks.no
  resources:
  - networktests/finalizers
  verbs:
  - update
- apiGroups:
  - edgeworks.no
  resources:
  - networktests/status
  verbs:
  - get
  - patch
  - update
