{{- if .Values.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "networktester.fullname" . }}
  labels:
    {{- include "networktester.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "networktester.selectorLabels" . | nindent 4 }}
{{- end }}
