# Default values for networktester.

# When set, will restrict watching of Networktest CRs only from that namespace
# Could be different from  installation namespace, but easiest to keep them together.
# When unset (default), will watch for all namespaces
restrictNamespace: ""

installCrds: true

image:
  repository: ghcr.io/edgeworks-as/networktester
  pullPolicy: IfNotPresent
  tag: "" # Overrides appVersion from Chart.yaml if needed

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "networktester"

serviceMonitor:
  create: true
  annotations:
    scrape-by: prometheus
  labels:
    serviceMonitorSelector: prometheus

service:
  create: true

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 128Mi

# Extras that could be useful to tweak
replicaCount: 1
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
